### ISSUE TITLE
4.1 Issue

### ISSUE THREAD

**Issue by drewdus42** [HungryProton/scatter#122]
Currently testing on 4.1 RC2, but same error on RC1

I get the following error on like all the resources...

`  scene/resources/resource_format_text.cpp:447 - res://addons/proton_scatter/src/shapes/gizmos_plugin/components/path_panel.tscn:4 - ext_resource, invalid UID: uid://b2b62ko7v686h - using text path instead: res://addons/proton_scatter/icons/curve_select.svg`

**Comment by drewdus42** [comment]
also getting this error when i add a proton scatter to a scene:

`  Adding children to a node inside the SceneTree is only allowed from the main thread. Use call_deferred("add_child",node).`

**Comment by HungryProton** [comment]
Second issue should have been fixed a few weeks ago in b2f7c5b868822b0645b47c6b04bdde1a6aa40867
(Asset lib version is not up-to-date yet)

I'll look into the first issue, but I suspect this is an engine bug.

**Comment by drewdus42** [comment]
Must have been an RC1 and RC2 bug. 
I just tried on RC3 cause the patch notes mentioned buggy resource path loading workaround.
Also replaced with github version. 
It's all good now.

**Comment by sebastianrueckerai** [comment]
Hi! I am still encountering `add_child: Adding children to a node inside the SceneTree is only allowed from the main thread. Use call_deferred("add_child",node).` with 4.1 stable and the Scatter version from the Asset lib. I then downloaded the repo instead which solved the issue. People who use the asset lib version may still experience the bug.

**Comment by drewdus42** [comment]
Yeah they mentioned the one on asset lib is behind

**Comment by HungryProton** [comment]
I've updated the asset lib version, should be fixed now.
